# -*- conf -*-
[package]
name = "tetris"
version = "0.1.0"
authors = ["Vladimir Lagunov <lagunov.vladimir@gmail.com>"]


[dependencies]
sdl2 = "0.9.*"
sdl2-sys = "0.6.*"
rand = "0.3.*"
time = "0.1.*"
argparse = "0.2.*"